 - name: ensure we have directories set up
   file: path={{ item }} state=directory mode=0755
   with_items:
     - /var/log/ecs
     - /etc/ecs
     - /var/lib/ecs/data
   tags: configure

 - name: create configuration template
   file: path=/etc/ecs/ecs.config state=file mode=0644
   tags: configure

 - name: ensure we have dependencies installed
   pip: name=docker-py state=present
   tags: dependencies

 - name: set up system variable for ecs task
   sysctl:
     name: net.ipv4.conf.all.route_localnet
     value: 1
     state: present
   tags: configure

 - name: set up iptables rules for ecs task [OUTPUT]
   iptables:
     table: nat
     chain: OUTPUT
     protocol: tcp
     match: tcp
     destination: 169.254.170.2
     destination_port: 80
     jump: REDIRECT
     to_ports: 51679
   become: yes
   tags:
     - configure
     - iptables

 - name: set up iptables rules for ecs task [PREROUTING]
   iptables:
     table: nat
     chain: PREROUTING
     protocol: tcp
     destination: 169.254.170.2
     destination_port: 80
     jump: DNAT
     to_destination: 127.0.0.1:51679
   become: yes
   tags:
     - configure
     - iptables

 - name: run docker container
   docker:
     name: ecs-agent
     image: amazon/amazon-ecs-agent:latest
     state: started
     restart_policy: on-failure
     restart_policy_retry: 10
     net: host
     env:
       ECS_CLUSTER: cycloid-cluster
       ECS_ENABLE_TASK_IAM_ROLE: true
       ECS_ENABLE_TASK_IAM_ROLE_NETWORK_HOST: true
       ECS_DATADIR: /data
       ECS_LOGFILE: /log/ecs-agent.log
       ECS_LOGLEVEL: info
     volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /var/log/ecs/:/log
     - /var/lib/ecs/data:/data
   tags: install
