- name: update repo
  apt:
    update_cache: yes
  tags: update

- name: install kibana
  package:
    name: kibana
    state: present
    allow_unauthenticated: yes
  tags: install

- name: enable and start kibana
  service:
    name: kibana
    enabled: yes
    state: started
  tags: configure
