- name: install iptables [Ubuntu/Debian]
  apt: name=iptables-persistent state=present
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
  tags: install

- name: install iptables [CentOS/RedHat]
  yum: name=iptables state=present
  when: ansible_distribution == "CentOS" or ansible_distribution == "Red Hat Enterprise Linux"
  tags: install

- name: configure iptables
  copy: src=iptables-config dest=/etc/sysconfig/iptables-config force=yes
  notify: restart iptables
  when: ansible_distribution == "CentOS" or ansible_distribution == "Red Hat Enterprise Linux"
  tags: configure

# Warning! Last tasks works only for >=2.0 version

- name: permit necessary input ports
  iptables: chain=INPUT destination_port={{ item }} protocol=tcp match=tcp jump=ACCEPT
  with_items:
     - 22
     - 722
     - 1935
     - 80
     - 443
     - 3306
     - 8080
     - 8086
     - 8087
     - 8088
  notify: save iptables
  tags: configure

- name: deny everything that's not permitted
  iptables: chain=INPUT protocol=tcp match=tcp jump=DROP
  notify: save iptables
  tags: 
     - configure
     - drop
