- name: unlink deafault vhost
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  tags:
    - configure

- name: place suitable vhost
  template:
    src: "{{ inventory_hostname }}.j2"
    dest: "/etc/nginx/sites-available/{{ vhost }}"
  tags:
    - vhost
    - configure

- name: link vhost
  file:
    src: "/etc/nginx/sites-available/{{ vhost }}"
    dest: "/etc/nginx/sites-enabled/{{ vhost }}"
    state: link
  notify: reload nginx
  tags:
    - configure
