- name: ensure nginx has been started
  service: name=nginx state=started

- name: remove deafault vhost
  file: path=/etc/nginx/conf.d/default.conf state=absent
  tags: configure

- name: create directory for nginx proxy cache
  file: name={{ proxy_cache_dir }} state=directory owner=nginx group=nginx mode=0700
  tags: configure

- name: change nginx config file
  template: src=nginx.j2 dest=/etc/nginx/nginx.conf force=yes
  notify: restart nginx
  tags: configure

- name: change nginx vhost file
  template: src={{ nginx_vhost }}.j2 dest=/etc/nginx/{{ conf_directory }}/{{ nginx_vhost }}.conf force=yes
  notify: restart nginx
  tags: configure