- name: update repo cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  tags: repo

- name: install CA certificates support + pip
  apt:
    name: "{{ item }}"
    state: present
  with_items:
   - apt-transport-https
   - ca-certificates
   - apparmor
   - python-pip
  tags: ca

- name: add gpg key
  apt_key:
    keyserver: "hkp://p80.pool.sks-keyservers.net:80"
    id: "58118E89F3A912897C070ADBF76221572C52609D"
  tags: ca

- name: add docker repo
  apt_repository:
    repo: 'deb https://apt.dockerproject.org/repo ubuntu-xenial main'
    state: present
  tags: repo

- name: update repo cache one more time
  apt:
    update_cache: yes
  tags: repo

  # TODO! Copy the following 2 tasks to upgrade role

  # Что делает эта команда?
  # Достает список deb-пакетов, ищет образы ядра
  # и фильтрует названия пакетов в формате команды 'uname -r'

- name: get all possible kernel versions
  shell: "dpkg -l | grep -E 'linux-image-[0-9]' | awk '{print $2}' | sed 's/linux-image-//g'"
  register: kernel_images
  tags: kernel

- name: install extra drivers
  apt:
    name: "linux-image-extra-{{ item }}"
    state: present
    allow_unauthenticated: yes
  with_items: "{{ kernel_images.stdout_lines }}"
  tags: kernel

- name: install docker python module
  pip:
    name: docker-py
    state: present
  tags: module