  #works only on ansible>2.1

 - name: install docker package
   apt: name=docker-engine state=present allow_unauthenticated=yes
   tags: install

 - name: ensure pip is installed
   apt: name=python-{{ item }} state=present allow_unauthenticated=yes
   with_items:
    - pip
    - virtualenv
   tags:
    - compose
    - install

 - name: install docker compose
   pip: name=docker-compose state=present
   tags:
    - compose
    - install

 - name: ensure docker has been started
   service: name=docker state=started
   tags: service