- name: update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 86400
  tags:
    - install
    - cache

- name: install apache
  package:
    name: apache2
    state: present
  tags: install