- name: setup mail relay to send notifications
  include_role:
    name: mail_relay

- name: install fail2ban
  package:
    name: fail2ban
    state: present
  tags: install

- name: setup nginx environment
  include: nginx-filters.yml

- name: start fail2ban
  service:
    name: fail2ban
    state: started
    enabled: yes
  tags: service

- name: check fail2ban status
  include: status.yml
  tags: status
