---

- name: set facts to install nginx
  set_fact:
    vhost: jenkins
    server_name: jenkins.example.com
    proxy_port: 8080
  tags: nginx

- name: install nginx
  include_role:
    name: nginx
  tags: nginx

- name: install java
  include_role:
    name: java_oracle_deb
  when: java_setup == True
  tags: java

- include: master_setup.yml
