- name: ensure we have tool for apt repo configuration
  apt:
    name: "{{ item }}"
    state: present
    allow_unauthenticated: yes
  with_items:
    - software-properties-common
    - python-software-properties
    - apt-transport-https
  tags:
   - repo

- name: add java repo [Debian/Ubuntu]
  apt_repository:
    repo: 'ppa:webupd{{ java_major_version }}team/java'
    state: present
  tags:
   - repo
   - java

- name: update repo [Debian/Ubuntu]
  apt:
    update_cache: yes
  tags:
   - update
   - java

- name: accept Oracle policy
  debconf:
    name: oracle-java8-installer
    question: shared/accepted-oracle-license-v1-1
    value: true
    vtype: select
  tags:
   - install
   - java

- name: install jdk [Debian/Ubuntu]
  apt:
    name: "{{ item }}"
    state: present
    allow_unauthenticated: yes
  with_items:
    - oracle-java{{ java_major_version }}-installer
    - oracle-java{{ java_major_version }}-set-default
    - ca-certificates
  tags:
   - install
   - java
