- name: setup nginx [1]
  set_fact:
    nginx_auth: True
  tags: nginx

- name: setup nginx[2]
  include_role:
    name: nginx
  tags: nginx

- name: setup elasticsearch
  include_role:
    name: elasticsearch
  tags: elasticsearch

- name: setup logstash
  include: logstash.yml
  tags: logstash

- name: setup Kibana
  include: kibana.yml
  tags: kibana
