- name: get gpg key [Debian/Ubuntu]
  apt_key: url=https://ftp-master.debian.org/keys/archive-key-6.0.asc state=present
  tags: 
    - repo
    - key

- name: get ossec-agent repo [Debian/Ubuntu]
  apt_repository: repo='deb http://ossec.wazuh.com/repos/apt/ubuntu trusty main' state=present
  tags: repo

- name: update repo [Debian/Ubuntu]
  apt: update_cache=yes
  tags: 
    - update
    - repo

- name: install ossec-agent
  package: name=ossec-hids-agent state=present force=yes
  tags: install