- name: update cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  tags: cache

- name: install packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - php
    - php-fpm
    - php-enchant
    - php-mbstring
    - php-mysql
    - php-xml
  tags: install
