- name: ensure we have unzip installed
  package: name=unzip state=present
  tags: dependencies

- name: download nomad
  get_url: url=https://releases.hashicorp.com/nomad/{{ nomad_version }}/nomad_{{ nomad_version }}_linux_amd64.zip dest=/tmp/nomad_{{ nomad_version }}.zip
  tags: download

- name: setup nomad
  unarchive: src=/tmp/nomad_{{ nomad_version }}.zip dest=/usr/bin copy=no
  tags: install

- name: make directory for nomad logs and configs
  file: path={{ item }} state=directory mode=0755
  with_items:
    - '{{ log_dir }}'
    - '{{ config_dir }}'
    - '{{ data_dir }}'
  tags: configure

- include: nomad_server.yml
  when: inventory_hostname == '{{ nomad_server }}'

- include: nomad_agent.yml
  when: inventory_hostname != '{{ nomad_server }}'