- name: check which process eats more memory
  shell: "ps aux | sort -nk +4 | tail | awk '{print $4 \"\t\" $11}'"
  register: table_memory
  tags:
    - memory
    - check

- name: print memory table
  debug:
    msg: "{{ table_memory.stdout.split('\n').replace('\\t', '    ') }}"
  tags:
    - memory
    - check

- name: get netstat information about listening ports
  shell: "netstat -tupln | grep -E 'tcp|udp'"
  register: netstat_info
  tags:
    - network
    - check

- name: print netstat_info
  debug:
    msg: "{{ netstat_info.stdout.split('\n') }}"
  tags:
    - network
    - check
