- name: reconfigure netfilter variables
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value.current }}"
    state: present
    reload: yes
  with_dict: "{{ netfilter_settings }}"
  tags:
   - nf_conntrack
   - netfilter
   - system_vars

- name: install iptables
  apt:
    name: "{{ item }}"
    state: present
  with_items:
   - iptables
   - iptables-persistent
  tags:
   - netfilter
   - iptables
   - install

- name: add iptables rules to drop malware tcp connections
  shell: '{{ item }}'
  with_items:
   - 'iptables -t mangle -A PREROUTING -m conntrack --ctstate INVALID -j DROP'
   - 'iptables -t mangle -A PREROUTING -p tcp ! --syn -m conntrack --ctstate NEW -j DROP'
   - 'iptables -t mangle -A PREROUTING -p tcp -m conntrack --ctstate NEW -m tcpmss ! --mss 536:65535 -j DROP'
  tags:
   - netfilter
   - iptables
   - configure

- name: save iptables rules[trusty]
  shell: service iptables-persistent save
  when: ansible_distribution ==  "Ubuntu" and ansible_distribution_release ==  '14.04'
  tags:
   - netfilter
   - iptables
   - configure

- name: save iptables rules[xenial]
  shell: service netfilter-persistent save
  when: ansible_distribution ==  "Ubuntu" and ansible_distribution_release !=  '14.04'
  tags:
   - netfilter
   - iptables
   - configure
