- name: update the cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  tags: software

- name: install software for maintenance and operations
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - ncdu
    - htop
    - tree
    - locate
    - curl
    - python
  tags: software

- name: make a system upgrade
  apt:
    upgrade: dist
  when: upgrade is defined
  tags:
   - software
   - upgrade
