- name: install software for maintenance and operations
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - ncdu
    - htop
    - tree
    - locate
    - curl
    - python
  tags: software
