 - name: reconfigure memory system variables on /proc/sys
   sysctl: name={{ item.variable }} value={{ item.value }} state=present reload=yes
   with_items:
    - { variable: 'vm.swappiness', value: 0 }
    - { variable: 'vm.dirty_background_ratio', value: 10 }
    - { variable: 'vm.dirty_ratio', value: 80 }
    - { variable: 'vm.dirty_expire_centisecs', value: 12000 }
    - { variable: 'vm.dirty_writeback_centisecs', value: 10000 }
    - { variable: 'vm.oom_dump_tasks', value: 1 }
    - { variable: 'vm.oom_kill_allocating_task', value: 1 }
    - { variable: 'vm.overcommit_memory', value: 0 }
    - { variable: 'vm.overcommit_ratio', value: 100 }
   tags:
    - memory 
    - system_vars

 - name: reconfigure network variables
   sysctl: name={{ item.variable }} value={{ item.value }} state=present reload=yes
   with_items:
    - { variable: 'net.core.somaxconn', value: 1000 }
    - { variable: 'net.core.netdev_max_backlog', value: 5000 }
    - { variable: 'net.core.rmem_max', value: 16777216 }
    - { variable: 'net.core.wmem_max', value: 16777216 }
    - { variable: 'net.ipv4.tcp_wmem', value: '4096 12582912 16777216' }
    - { variable: 'net.ipv4.tcp_rmem', value: '4096 12582912 16777216' }
    - { variable: 'net.ipv4.tcp_max_syn_backlog', value: 8096 }
    - { variable: 'net.ipv4.tcp_slow_start_after_idle', value: 0 }
    - { variable: 'net.ipv4.tcp_tw_reuse', value: 1 }
    - { variable: 'net.ipv4.ip_local_port_range', value: '10240 65535' }
    - { variable: 'net.ipv4.tcp_abort_on_overflow', value: 1 }
   tags:
    - network
    - system_vars

 - name: reconfigure cpu scheduler variables on /proc/sys
   sysctl: name={{ item.variable }} value={{ item.value }} state=present reload=yes
   with_items:
    - { variable: 'kernel.sched_migration_cost_ns', value: 10000000 }
    - { variable: 'kernel.sched_autogroup_enabled', value: 0 }
   tags:
    - cpu
    - system_vars

 - name: configure /sys variables
   shell: 'echo {{ item.value }} | sudo tee /sys/{{ item.variable }}'
   with_items:
    - { variable: 'kernel/mm/transparent_hugepage/enabled', value: 'never' }
   tags:
    - sys
    - system_vars

 - name: ensure necessary modules loaded
   modprobe: name={{ item }}
   with_items:
    - nf_conntrack
    - nf_conntrack_ipv4
   tags:
    - modules

 - name: change hostname
   hostname: name={{ hostname }}
   tags: hostname

##More info here: https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1518457/+index?comments=all
 - name: fix the hvm-kswapd bug
   file: name=/etc/udev/rules.d/40-vm-hotadd.rules state=touch
   when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '16.04'
   tags: kswapd
