 - name: ensure necessary modules loaded
   modprobe: name={{ item }}
   with_items:
    - nf_conntrack
    - nf_conntrack_ipv4
   tags:
    - modules
    - system_settings

 - name: change hostname
   hostname: name={{ hostname }}
   tags:
    - hostname
    - system_settings

##More info here: https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1518457/+index?comments=all
 - name: fix the hvm-kswapd bug
   file: name=/etc/udev/rules.d/40-vm-hotadd.rules state=touch
   when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '16.04'
   tags:
    - kswapd
    - system_settings
