 - name: ensure we have developers in server
   user: name={{ user }} group=developers shell=/bin/bash
   tags:
    - group
    - user

 - name: check user ssh key in local machine
   local_action: stat path="/home/cazorla19/.ssh/{{ user }}.pub"
   sudo: False
   register: key_file
   tags:
    - user
    - ssh
    - add

 - name: flush ssh user key if it locally exists
   authorized_key: user={{ user }} key="{{ lookup('file', '/home/cazorla19/.ssh/{{ user }}.pub') }}" state=present
   when: key_file.stat.exists == True
   tags:
    - user
    - ssh
    - add

 - name: check sudoers file in host template directory
   local_action: stat path={{ templates_dir }}/{{ inventory_hostname }}/sudoers.j2
   sudo: False
   register: sudo_file
   tags:
     - user
     - sudo

 - name: refresh sudoers on nodes
   template: src={{ templates_dir }}/{{ inventory_hostname }}/sudoers.j2 dest=/etc/sudoers
   when: sudo_file.stat.exists == True
   tags:
     - user
     - sudo
