- name: get gpg key [CentOS/RHEL]
  rpm_key: state=present key=http://packages.elastic.co/GPG-KEY-elasticsearch
  when: ansible_distribution == "CentOS" or ansible_distribution == "Red Hat Enterprise Linux"
  tags: 
    - repo
    - key

- name: get gpg key [Debian/Ubuntu]
  shell: "curl https://packages.elastic.co/GPG-KEY-elasticsearch --insecure | sudo apt-key add -"
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
  tags: 
    - repo
    - key

- name: get filebeat repo [CentOS/RHEL]
  copy: src=elastic-beats.repo dest=/etc/yum.repos.d/elastic-beats.repo force=yes
  when: ansible_distribution == "CentOS" or ansible_distribution == "Red Hat Enterprise Linux"
  tags: repo

- name: get filebeat repo [Debian/Ubuntu]
  apt_repository: repo='deb http://packages.elastic.co/beats/apt stable main' state=present
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
  tags: repo

- name: update repo [Debian/Ubuntu]
  apt: update_cache=yes
  tags: update
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: install filebeat
  package: name=filebeat state=present
  tags: install
