- name: get filebeat repo [CentOS/RHEL]
  copy: src=logstash.repo dest=/etc/yum.repos.d/logstash.repo force=yes
  when: ansible_distribution == "CentOS" or ansible_distribution == "Red Hat Enterprise Linux"
  tags: repo

- name: get logstash repo [Debian/Ubuntu]
  apt_repository: repo='deb http://packages.elastic.co/logstash/{{ logstash_version }}/debian stable main' state=present
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
  tags: repo

- name: update repo [Debian/Ubuntu]
  apt: update_cache=yes
  tags: update
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: install logstash
  package: name=logstash state=present allow_unauthenticated=yes
  tags: install

- name: enable and start logstash
  service: name=logstash enabled=yes state=started
  tags: 
    - configure
    - service

