- name: enable logstash
  service: name=logstash enabled=yes
  tags: 
    - configure
    - service

- name: check local configuration
  local_action: stat path={{ logstash_configs_local }}
  sudo: no
  register: local_configs
  tags:
    - configure
    - sync

- name: apply input/output configuration
  template: src={{ item }}.j2 dest=/etc/logstash/conf.d/{{ item }}.conf mode=0755
  with_items:
    - 02-beats-input.conf
    - 30-elasticsearch-output.conf
  notify: restart logstash
  when: local_configs.stat.exists == False
  tags: configure

- name: apply filter
  copy: src=roles/logstash/files/{{ filter }}-filter.conf dest=/etc/logstash/conf.d/{{ filter }}-filter.conf mode=0755 force=yes
  notify: restart logstash
  when: local_configs.stat.exists == False
  tags:
    - configure
    - filter

- name: sync logstash configuration directory
  synchronize: mode=push src={{ logstash_configs_local }}/{{ item }} dest=/etc/logstash recursive=yes
  with_items:
    - conf.d
    - patterns
  when: local_configs.stat.exists == True
  notify: restart logstash
  tags: sync

- name: test logstash configuration
  command: service logstash configtest
  changed_when: False
  tags:
    - configure
    - sync
