- name: setup consul daemon
  template:
    src: consul_agent.j2
    dest: /etc/systemd/system/consul-agent.service
  register: daemon
  tags: daemon

- name: reload systemd on Ubuntu 16 nodes
  shell: systemctl daemon-reload
  when: daemon.changed
  tags: daemon

- name: add Consul to startup
  service:
    name: consul-agent
    enabled: yes
  tags: startup

- name: update services
  copy:
    src: test_agent.json
    dest: "{{ config_dir }}/"
  notify: restart consul-agent
  tags:
   - discovery
   - health_check

- name: update watch
  copy:
    src: test_watch.json
    dest: "{{ config_dir }}/"
  notify: restart consul-agent
  tags:
    - discovery
    - watch

- name: start consul agent
  service:
    name: consul-agent
    state: started
  tags: service

- name: check consul service state
  shell: service consul-agent status
  register: consul_state
  tags: check

- name: print consul service state
  debug:
    msg: "{{ consul_state.stdout }}"
  tags: check

- name: restart consul-agent
  service:
    name: consul-agent
    state: restarted
  when: consul_restart is defined
  tags: restart
